mod binary_expression_tests;
mod block_expression_tests;
mod call_expression_tests;
mod curry_call_expression_tests;
mod function_expression_tests;
mod if_expression_tests;
mod instantiation_expression_tests;
mod prop_access_tests;
mod variable_expression_tests;
